### PR TITLE
v0.8.0

### PR DESCRIPTION
**Pull request by hawkw**
## v0.8.0

* Add `Opaque` variant to `destination.ProtocolHint`

### CODE REVIEW

**Comment by olix0r** [comment]
Is this really a breaking change?

**Comment by olix0r** [comment]
afaict this should be 0.7.1, unless we have an enum that needs updating.

**Comment by hawkw** [comment]
> afaict this should be 0.7.1, unless we have an enum that needs updating. -- if so, can we make it non-exhaustive?

This adds a new variant to an enum, which is a breaking change: https://github.com/linkerd/linkerd2-proxy-api/commit/b2f7219bbbd49449cac25fec013410663b4619d4#diff-e376e65ab87f7c7679472651d00eba584b6c134cd5ccf8a3b68f09e699944894R153-R157

I'm not sure if there's a way to get `prost` to add the `#[non_exhaustive]` attribute to generated enums, but I'll look into it. However, I think adding `#[non_exhaustive]` to an enum that is currently exhaustive is _also_ a breaking change, since any exhaustive matching on that enum's variants would become invalid. Adding `#[non_exhaustive]` would be a nice way to avoid future breaking changes from new `oneof` variants, though...

**Comment by hawkw** [comment]
It looks like we could use the [`enum_attribute` method in `prost-build`](https://docs.rs/prost-build/latest/prost_build/struct.Config.html#method.enum_attribute) to put `#[non_exhaustive]` on some or all of the enums generated for `oneof`s in the proto definition.

**Review by olix0r — APPROVED** [review]

**Review by kleimkuhler — APPROVED** [review]

**Pull request merged**
